version: '3'

services:
  cache:
    container_name: redis-container
    image: 'redis'
    restart: always
    volumes:
      - ./.data:/data/cache
    ports:
      - '6379:6379'

  api:
    container_name: api-container
    build: .
    image: node-cache-api
    restart: always
    command: npm start
    volumes:
      - .:/usr/src/api
    ports:
      - '3000:3000'
    links:
      - cache
